# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  CACHE_DIR: $(Pipeline.Workspace)/.cache

steps:
  - bash: |
      mkdir -p $(CACHE_DIR)
      curl -sS -o $(CACHE_DIR)/sqlcl-latest.zip \
           https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
      echo Unzipping to $(CACHE_DIR)/sqlcl
      unzip   -qq -d $(CACHE_DIR) $(CACHE_DIR)/sqlcl-latest.zip
      rm -rf $(CACHE_DIR)/sqlcl-latest.zip
      export PATH=$PATH:$(STAGE_DIR)/sqlcl/bin
      sql -v
    displayName: 'Install Oracle sqlcl'