# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  CACHE_DIR: $(Pipeline.Workspace)/.cache
  SQLCL_DIR: $(Build.BinariesDirectory)/sqlcl
  UTPLSQL_DIR: $(Build.BinariesDirectory)/utPLSQL
  UTPLSQL_CLI_DIR: $(Build.BinariesDirectory)/utPLSQL-cli
  UTPLSQL_CLI_VERSION: 'v3.1.8'
  UTPLSQL_VERSION: 'v3.1.11' 
  DOCKHER_HUB_REPO: 'utplsqlv3/oracledb'
  # Timezone needed for working with Oracle DB
  TZ: UTC
  ORACLE_VERSION: '19.3'
  DOCKER_OPTIONS: '--shm-size=1g'
  DB_SYS_PASSWORD: oracle
  DB_USER: ut3_demo
  DB_PASS: ut3_demo  
steps:
  - task: CacheBeta@0
    inputs:
      path: '$(CACHE_DIR)'
      key: './*'
  - bash: |
      echo "##vso[task.prependpath]$(UTPLSQL_CLI_DIR)/bin"
      echo "##vso[task.prependpath]$(SQLCL_DIR)/bin"
      mkdir -p $(CACHE_DIR)
    displayName: 'Pre jobs task'

  - bash: |    
      curl -sS -o $(Build.BinariesDirectory)/sqlcl-latest.zip \
           https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
      echo Unzipping to $(Build.BinariesDirectory)/sqlcl
      unzip   -qq -d $(Build.BinariesDirectory) $(Build.BinariesDirectory)/sqlcl-latest.zip
      rm -rf $(Build.BinariesDirectory)/sqlcl-latest.zip
      # Relates to : https://community.oracle.com/tech/developers/discussion/4490418/sqlcl-production-build-21-3-0-278-1045-throwing-warning-terminal-cannot-be-created-paused
      export JAVA_TOOL_OPTIONS=-Dorg.jline.terminal.dumb=true
      sql -v
    displayName: 'Install Oracle sqlcl'

  - bash: |
      curl -Lk -o $(UTPLSQL_CLI_DIR).zip "https://github.com/utPLSQL/utPLSQL-cli/releases/download/$(UTPLSQL_CLI_VERSION)/utPLSQL-cli.zip"
      cd $(Build.BinariesDirectory)
      unzip $(UTPLSQL_CLI_DIR).zip && chmod -R u+x $(UTPLSQL_CLI_DIR)
      cp $(SQLCL_DIR)/lib/ojdbc8.jar $(UTPLSQL_CLI_DIR)/lib && cp $(SQLCL_DIR)/lib/orai18n.jar $(UTPLSQL_CLI_DIR)/lib
    displayName: 'Install utPLSQL-cli'

  - bash: |
      git clone --depth=1 --branch=${UTPLSQL_VERSION} https://github.com/utPLSQL/utPLSQL.git ${UTPLSQL_DIR}
      # Needed for older versions of utPLSQL.
    displayName: 'Download utPLSQL'

  - bash: |
      docker login
      # download Oracle Database docker image from private repo and start the DB
      time docker pull ${DOCKHER_HUB_REPO}:${ORACLE_VERSION}
      # start the docker container (DB)
      time docker run -d --name ${ORACLE_VERSION} ${DOCKER_OPTIONS} -p 1521:1521 ${DOCKHER_HUB_REPO}:${ORACLE_VERSION}
      # Wait for DB startup
      time docker logs -f ${ORACLE_VERSION} | grep -m 1 "DATABASE IS READY TO USE!" --line-buffered
    displayName: 'Start Oracle DB Docker container'
  - bash: .travis/install_utplsql.sh
    displayName: 'Install utPLSQL'