# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  CACHE_DIR: $(Pipeline.Workspace)/.cache
  SQLCL_DIR: $(Build.BinariesDirectory)/sqlcl
  UTPLSQL_DIR: $(Build.BinariesDirectory)/utPLSQL
  UTPLSQL_CLI_DIR: $(Build.BinariesDirectory)/utPLSQL-cli
  
steps:
  - bash: |
      echo "##vso[task.prependpath]$(UTPLSQL_CLI_DIR)/bin"
      echo "##vso[task.prependpath]$(SQLCL_DIR)/bin"
      mkdir -p $(CACHE_DIR)
    displayName: 'Pre jobs task'

  - bash: |    
      curl -sS -o $(Build.BinariesDirectory)/sqlcl-latest.zip \
           https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
      echo Unzipping to $(Build.BinariesDirectory)/sqlcl
      unzip   -qq -d $(Build.BinariesDirectory) $(Build.BinariesDirectory)/sqlcl-latest.zip
      rm -rf $(Build.BinariesDirectory)/sqlcl-latest.zip
      sql -v
    displayName: 'Install Oracle sqlcl'