trigger: 
  - none

pool:
  vmImage: ubuntu-latest

extends:
  template: .azure_templates/t-pipeline-extend-cicd.yml
  parameters:
    buildDatabase:
      - createDatabase:
          - dbname: UTBUILD
            oracleVersion: "19c-se2-small"
            connectionString: "127.0.0.1:1521/ORCLCDB"
            dockerPortMap: "1521"
            dockerOptions: "--shm-size=1g"

    #DeployDatabase:
    