trigger: 
  - none

pool:
  vmImage: ubuntu-latest

variables:
# Using this variable, the template references the correct variable template file (vars-dev.yaml, vars-qa.yaml or vars-prd.yaml) from the vars folder.
  - template: .azure_templates/vars/vars-global.yml  
  - name: SQLCL_DIR
    value: $(Build.BinariesDirectory)/sqlcl
  - name : UTPLSQL_DIR
    value: $(Build.BinariesDirectory)/utPLSQL
  - name : UTPLSQL_CLI_DIR
    value: $(Build.BinariesDirectory)/utPLSQL-cli
  - name : UTPLSQL_CLI_VERSION
    value:  'v3.1.8'
  - name : UTPLSQL_VERSION
    value:  'v3.1.11' 
  - name : DB_USER
    value:  ut3_demo
  - name : DB_PASS
    value:  ut3_demo
  
extends:
  template: .azure_templates/t-pipeline-extend-cicd.yml
  parameters:
    buildDatabase:
      - containerRegistry: ${{ variables.containerRegistry }}
        dockerRepo: ${{ variables.dockerRepo }}
        packages:
          - name: sqlcl
            download_location: "$(Build.BinariesDirectory)/sqlcl-latest.zip"
            unpack_location: "$(Build.BinariesDirectory)"
            url: ${{ variables.sqlclUrl }}
            archive: "zip"
            addtoPath: "$(SQLCL_DIR)/bin"
          - name: utlplsqlcli
            download_location: "$(Build.BinariesDirectory)/utPLSQL-cli.zip"
            unpack_location: "$(Build.BinariesDirectory)"
            url: ${{ variables.utplsqlcliUrl }}
            archive: "zip"
            addToPath: "$(UTPLSQL_CLI_DIR)/bin"
        createDatabase:
          - dbname: UTBUILD
            oracleVersion: "19c-se2-small"
            connectionString: "127.0.0.1:1521/ORCLCDB"
            dockerPortMap: "1521"
            dockerOptions: "--shm-size=1g"

    #DeployDatabase:
    