parameters:
  - name: createDatabase
    type: object
    default:
      - name: dbname
        default: ""
      - name: oracleVersion
        default: ""  
      - name: dockerOptions
        default: "--shm-size=1g"
      - name: dockerPortMap
        default: "1521"
      - name: connectionString
        default: ""   

jobs:
  - job: BuildDatabase
    displayName: Build Database
    variables:
    # Using this variable, the template references the correct variable template file (vars-dev.yaml, vars-qa.yaml or vars-prd.yaml) from the vars folder.
    - template: ../vars/vars-global.yml    
    steps:
      - template: ../tasks/t-create-docker-database.yml
        parameters:
          containerRegistry: ${{ variables.containerRegistry }}
          dockerRepo: ${{ variables.dockerRepo }}
          createDatabase: ${{ parameters.createDatabase }}