parameters:
  - name: containerRegistry
    default: ""
  - name: dockerRepo
    default: ""
  - name: createDatabase
    type: object
    default:
      - name: dbname
        default: ""
      - name: oracleVersion
        default: ""  
      - name: dockerOptions
        default: "--shm-size=1g"
      - name: dockerPortMap
        default: "1521"
      - name: connectionString
        default: ""   

steps:
  - task: Docker@2
    displayName: Docker Login
    inputs:
      containerRegistry: ${{ parameters.containerRegistry }}
      command: 'login'
  - ${{ each builddatabases in parameters.createDatabase }}:      
    - bash: |
        # download Oracle Database docker image from private repo and start the DB
        time docker pull ${{ parameters.dockerRepo }}:${{ builddatabases.oracleVersion }}
        # start the docker container (DB)
        time docker run -d --name ${{ builddatabases.dbname }} ${{ builddatabases.dockerOptions }} -p 1521:${{ builddatabases.dockerPortMap }} ${{ parameters.dockerRepo }}:${{ builddatabases.oracleVersion }}
        # Wait for DB startup
        time docker logs -f ${{ builddatabases.oracleVersion }} | grep -m 1 "DATABASE IS READY TO USE!" --line-buffered
      displayName: 'Start Oracle DB Docker container: ${{ builddatabases.dbname }}:${{ builddatabases.oracleVersion }}'      