parameters:
  - name: createDatabase
    type: object
    default:
      - name: dbname
        default: ""
      - name: oracleVersion
        default: ""  
      - name: dockerOptions
        default: "--shm-size=1g"
      - name: dockerPortMap
        default: "1521"
      - name: connectionString
        default: ""    
stages:
  - stage: BuildDatabase
    displayName: Build Database
    jobs:
      - template: jobs/t-extend-build-job.yml
        parameters:
          createDatabase: ${{ parameters.createDatabase }}
    