parameters:
  - name: containerRegistry
    default: ""
  - name: dockerRepo
    default: ""
  - name: packages
    type: object
    default:
      - name: name
        default: ""  
      - name: download_location
        default: ""
      - name: unpack_location
        default: "$(Build.BinariesDirectory)"    
      - name: url
        default: ""
      - name: archive
        default: "zip"
      - name: addToPath
        default: ""      
  - name: createDatabase
    type: object
    default:
      - name: dbname
        default: ""
      - name: oracleVersion
        default: ""  
      - name: dockerOptions
        default: "--shm-size=1g"
      - name: dockerPortMap
        default: "1521"
      - name: connectionString
        default: ""   

jobs:
  - job: BuildDatabase
    displayName: Build Database  
    steps:
      - template: t-task-extend-create-docker-database.yml
        parameters:
          containerRegistry: ${{ parameters.containerRegistry }}
          dockerRepo: ${{ parameters.dockerRepo }}
          createDatabase: ${{ parameters.createDatabase }}
      - template: t-task-extend-download-binaries.yml
        parameters:
          packages: ${{ parameters.packages }}  