parameters:
  - name: containerRegistry
    default: ""
  - name: dockerRepo
    default: ""
  - name: packages
    type: object
    default:
      - name: name
        default: ""  
      - name: download_location
        default: ""
      - name: unpack_location
        default: "$(Build.BinariesDirectory)"    
      - name: url
        default: ""
      - name: archive
        default: "zip"
      - name: addToPath
        default: ""      
  - name: createDatabase
    type: object
    default:
      - name: dbname
        default: ""
      - name: oracleVersion
        default: ""  
      - name: dockerOptions
        default: "--shm-size=1g"
      - name: dockerPortMap
        default: "1521"
      - name: connectionString
        default: ""
  - name: scripts
    type: object
    default:
      - name: work_dir
        default: ""
      - name: user
        default: ""
      - name: password
        default: ""
      - name: script
        default: ""
      - name: displayName
        default: ""            
  - name: installsource
    type: object
    default:
      - name: work_dir
        default: ""
      - name: user
        default: "sys"
      - name: password
        default: "oracle"
      - name: connectionString
        default: ""
      - name: masterchangelogfile
        default: ""

jobs:
  - job: BuildDatabase
    displayName: Build Database  
    steps:
      - template: t-task-extend-download-binaries.yml
        parameters:
          packages: ${{ parameters.packages }}    
      - template: t-task-extend-create-docker-database.yml
        parameters:
          containerRegistry: ${{ parameters.containerRegistry }}
          dockerRepo: ${{ parameters.dockerRepo }}
          createDatabase: ${{ parameters.createDatabase }}
      - ${{ each script in parameters.scripts }}:
        - template: t-extend-sqlcl.yml
          parameters:
            work_dir: ${{ script.work_dir}}
            user: ${{ script.user}}
            password: ${{ script.password}}
            connectionString: ${{ trg_db.connectionString}}
            script: ${{ script.script}}
          displayName: ${{ script.displayName}}          
      - template: t-task-extend-sqlcl-liquibase.yml
        parameters:
          installsource: ${{ parameters.installsource }}  