parameters:
  - name: buildDatabase
    type: object
    default:
      - name: downloadBinaries
        type: object
        default:
        - name: name
          default: ""  
        - name: download_location
          default: ""
        - name: unpack_location
          default: "$(Build.BinariesDirectory)"    
        - name: url
          default: ""
        - name: archive
          default: "zip"
        - name: addToPath
          default: ""    
      - name: createDatabase
        type: object
        default:
          - name: dbname
            default: ""
          - name: oracleVersion
            default: ""  
          - name: dockerOptions
            default: "--shm-size=1g"
          - name: dockerPortMap
            default: "1521"
          - name: connectionString
            default: ""
          - name: scripts
            type: object
            default:
              - name: work_dir
                default: ""
              - name: user
                default: ""
              - name: password
                default: ""
              - name: script
                default: ""
              - name: displayName
                default: ""
              

stages:
  - ${{ each builddatabases in parameters.buildDatabase }}:
    - template: t-stage-extend-build.yml
      parameters:
        downloadBinaries: $ {{ builddatabases.downloadBinaries }}
        createDatabase: ${{ builddatabases.createDatabase }}
        