parameters:
  - name: buildDatabase
    type: object
    default:
      - name: createDatabase
        type: object
        default:
          - name: dbname
            default: ""
          - name: oracleVersion
            default: ""  
          - name: dockerOptions
            default: "--shm-size=1g"
          - name: dockerPortMap
            default: "1521"
          - name: connectionString
            default: ""   

stages:
  - ${{ each builddatabases in parameters.buildDatabase }}:
    - template: t-stage-extend-build.yml
      parameters:
        createDatabase: ${{ builddatabases.createDatabase }}