parameters:
  - name: buildDatabase
    type: object
    default:
      - name: containerRegistry
        default: ""
      - name: dockerRepo
        default: ""  
      - name : connectionString
        default : ""
      - name: environment
        default: ""    
      - name: packages
        type: object
        default:
          - name: name
            default: ""  
          - name: download_location
            default: ""
          - name: unpack_location
            default: "$(Build.BinariesDirectory)"    
          - name: url
            default: ""
          - name: archive
            default: "zip"
          - name: addToPath
            default: ""             
      - name: createDatabase           
        type: object
        default:
          - name: dbname
            default: ""
          - name: oracleVersion
            default: ""  
          - name: dockerOptions
            default: "--shm-size=1g"
          - name: dockerPortMap
            default: "1521"
          - name: connectionString
            default: ""
      - name: gitCheckoutDetails
        type: object
        default:
          - name: gitRepo
            default: ""
          - name: branch
            default: ""
          - name: checkoutDir
            default: ""             
      - name: scripts
        type: object
        default:
          - name: work_dir
            default: ""
          - name: user
            default: ""
          - name: password
            default: ""
          - name: script
            default: ""
          - name: displayName
            default: ""               
      - name: installsource
        type: object
        default:
          - name: work_dir
            default: ""
          - name: user
            default: "sys"
          - name: password
            default: "oracle"
          - name: connectionString
            default: ""
          - name: masterchangelogfile
            default: ""
      - name: execute_tests
        type: object
        default:
          - name : work_dir
            default: $(Build.SourcesDirectory)
          - name: connectionString
            default: ""
          - name: test_user
            default: ""  
          - name: test_pwd
            default: ""
          - name: source_path
            default: ""
          - name: test_path
            default: ""
          - name: options
            default: ""


stages:
  - ${{ each builddatabases in parameters.buildDatabase }}:
    - template: t-stage-extend-build.yml
      parameters:
        createDatabase: ${{ builddatabases.createDatabase }}
        packages: ${{ builddatabases.packages }}
        containerRegistry: ${{ builddatabases.containerRegistry }}
        dockerRepo: ${{ builddatabases.dockerRepo }}
        installsource: ${{ builddatabases.installsource }}
        scripts: ${{ builddatabases.scripts }}
        gitCheckoutDetails: ${{ builddatabases.gitCheckoutDetails }}
        execute_tests: ${{ builddatabases.execute_tests }}