parameters:
  - name: containerRegistry
    default: ""
  - name: dockerRepo
    default: ""  
  - name: createDatabase
    type: object
    default:
      - name: dbname
        default: ""
      - name: oracleVersion
        default: ""  
      - name: dockerOptions
        default: "--shm-size=1g"
      - name: dockerPortMap
        default: "1521"
      - name: connectionString
        default: ""    
stages:
  - stage: BuildDatabase
    displayName: Build Database
    jobs:
      - template: t-job-extend-build.yml
        parameters:
          createDatabase: ${{ parameters.createDatabase }}
          containerRegistry: ${{ parameters.containerRegistry }}
          dockerRepo: ${{ parameters.dockerRepo }}          
    