parameters:
  - name: containerRegistry
    default: ""
  - name: dockerRepo
    default: ""  
  - name: packages
    type: object
    default:
      - name: name
        default: ""  
      - name: download_location
        default: ""
      - name: unpack_location
        default: "$(Build.BinariesDirectory)"    
      - name: url
        default: ""
      - name: archive
        default: "zip"
      - name: addToPath
        default: ""        
  - name: createDatabase
    type: object
    default:
      - name: dbname
        default: ""
      - name: oracleVersion
        default: ""  
      - name: dockerOptions
        default: "--shm-size=1g"
      - name: dockerPortMap
        default: "1521"
      - name: connectionString
        default: ""    
stages:
  - stage: BuildDatabase
    displayName: Build Database
    jobs:
      - template: t-job-extend-build.yml
        parameters:
          createDatabase: ${{ parameters.createDatabase }}
          packages: ${{ parameters.packages }}
          containerRegistry: ${{ parameters.containerRegistry }}
          dockerRepo: ${{ parameters.dockerRepo }}          
    