parameters:
  - name: enableDownload
    type: boolean
    default: true
  - name: packages
    type: object
    default:
      - name: name
        default: ""  
      - name: download_location
        default: ""
      - name: unzip_location
        default: "$(Build.BinariesDirectory)"    
      - name: url
        default: ""
      - name: clean
        type: boolean
        default: true

stages:
  - ${{ if parameters.enableDownload }}:
    - stage: DownloadBinaries
      pool:
        vmImage: ubuntu-latest
      jobs:
        - job: DownloadBinaries
          displayName: Download Build Binaries
          steps:
            - ${{ each package in parameters.packages }}:
              - bash: |    
                  curl -Lk -o ${{package.download_location}} \
                        ${{package.url}}
                  echo Unzipping to ${{package.unzip_location}}
                  unzip   -qq -d ${{package.unzip_location}} ${{package.download_location}}
                  chmod -R u+x ${{package.unzip_location}}
                displayName: 'Download ${{package.name}}'
              - ${{ if package.clean }}:
                - bash: |    
                    rm -rf ${{package.download_location}}
                  displayName: 'Clean zip ${{package.name}}'             
