name: Build and deploy snapshot

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:

    env:
      UTPLSQL_VERSION: ${{matrix.utplsql-version}}
      DB_IMAGE: ${{matrix.db_image}}

    runs-on: ubuntu-latest
    startegy:
      matrix:
        utplsql-version: [develop, v3.0.0, v3.1.6, v3.1.11]
        db_image: gvenzl/oracle-xe:11-full

    services:
      oracle:
        image: ${{matrix.db_image}}
        env:
          ORACLE_PASSWORD: oracle
        ports:
          - 1521:1521
#        options: >-
#          --health-cmd healthcheck.sh
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install utPLSQL ${{matrix.utplsql-version}}
        run: echo Installing ${UTPLSQL_VERSION} && sh ${{ github.workspace }}/scripts/1_install_utplsql.sh

      - name: Install utPLSQL-cli
        run: curl -Lk -o utPLSQL-cli.zip "https://github.com/utPLSQL/utPLSQL-cli/releases/download/v3.1.8/utPLSQL-cli.zip" && unzip utPLSQL-cli.zip && chmod -R u+x utPLSQL-cli

      - name: Install demo project
        run: sh ${{ github.workspace }}/scripts/2_install_demo_project.sh

      - name: Install unit tests
        run: sh ${{ github.workspace }}/scripts/3_install_tests.sh

      - name: Install run tests
        run: sh ${{ github.workspace }}/scripts/4_run_tests.sh

